require:
  - rubocop-rails
  - rubocop-performance

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.0.0
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false
