class ApplicationRecord < ActiveRecord::Base
  # Determines if one of the attributes passed in is the inheritance column,
  # and if the inheritance column is attr accessible, it initializes an
  # instance of the given subclass instead of the base class.
  def self.new: (?untyped? attributes) ?{ () -> untyped } -> untyped
end
